INSERT INTO ITEMS (NAME, PRICE, CATEGORY, STATUS) VALUES
-- Accessories
('Leather Wallet', 26.00, 'Accessories', 'AVAILABLE'),
('Designer Sunglasses', 50.00, 'Accessories', 'AVAILABLE'),
('Elegant Silk Scarf', 40.00, 'Accessories', 'AVAILABLE'),
('Luxury Handbag', 120.00, 'Accessories', 'AVAILABLE'),
('Classic Wristwatch', 85.00, 'Accessories', 'AVAILABLE'),
('Engraved Keychain', 16.00, 'Accessories', 'AVAILABLE'),
('Custom Phone Case', 20.00, 'Accessories', 'AVAILABLE'),
('Stylish Fedora Hat', 35.00, 'Accessories', 'AVAILABLE'),
('Leather Belt', 33.00, 'Accessories', 'AVAILABLE'),
('Minimalist Cardholder', 23.00, 'Accessories', 'AVAILABLE'),

-- Jewelry
('Gold-Plated Necklace', 80.00, 'Jewelry', 'AVAILABLE'),
('Diamond Stud Earrings', 200.00, 'Jewelry', 'AVAILABLE'),
('Pearl Bracelet', 60.00, 'Jewelry', 'AVAILABLE'),
('Personalized Name Pendant', 90.00, 'Jewelry', 'AVAILABLE'),
('Sterling Silver Ring', 46.00, 'Jewelry', 'AVAILABLE'),
('Luxury Watch (Men)', 250.00, 'Jewelry', 'AVAILABLE'),
('Birthstone Charm Bracelet', 100.00, 'Jewelry', 'AVAILABLE'),
('Rose Gold Bangle', 66.00, 'Jewelry', 'AVAILABLE'),
('Cubic Zirconia Earrings', 36.00, 'Jewelry', 'AVAILABLE'),
('Handmade Beaded Bracelet', 28.00, 'Jewelry', 'AVAILABLE'),

-- Electronics
('Wireless Earbuds', 80.00, 'Electronics', 'AVAILABLE'),
('Smartwatch', 130.00, 'Electronics', 'AVAILABLE'),
('Bluetooth Speaker', 70.00, 'Electronics', 'AVAILABLE'),
('Mini Projector', 150.00, 'Electronics', 'AVAILABLE'),
('LED Light Strip', 25.00, 'Electronics', 'AVAILABLE'),
('Wireless Charging Pad', 30.00, 'Electronics', 'AVAILABLE'),
('Gaming Mouse', 60.00, 'Electronics', 'AVAILABLE'),
('Noise-Canceling Headphones', 200.00, 'Electronics', 'AVAILABLE'),
('Digital Photo Frame', 80.00, 'Electronics', 'AVAILABLE'),
('Portable Power Bank', 40.00, 'Electronics', 'AVAILABLE'),

-- Books
('Bestselling Novel', 20.00, 'Books', 'AVAILABLE'),
('Inspirational Self-Help Book', 23.00, 'Books', 'AVAILABLE'),
('Fantasy Book Collection', 50.00, 'Books', 'AVAILABLE'),
('Classic Literature Set', 60.00, 'Books', 'AVAILABLE'),
('Personalized Journal', 15.00, 'Books', 'AVAILABLE'),
('Sketchbook for Artists', 19.00, 'Books', 'AVAILABLE'),
('DIY Craft Book', 28.00, 'Books', 'AVAILABLE'),
('Poetry Anthology', 26.00, 'Books', 'AVAILABLE'),
('Science Fiction Bestseller', 35.00, 'Books', 'AVAILABLE'),
('Cookbook for Beginners', 30.00, 'Books', 'AVAILABLE'),

-- Perfumes and Fragrances
('Luxury Perfume (Men)', 90.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Luxury Perfume (Women)', 100.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Unisex Designer Fragrance', 80.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Essential Oil Gift Set', 46.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Floral-Scented Perfume', 70.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Citrus and Fresh Perfume', 75.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Oud and Musk Collection', 150.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Car Air Freshener Set', 20.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Aromatherapy Roll-On Perfume', 35.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Solid Perfume Compact', 40.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Sandalwood and Vanilla Mist', 45.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Rose Essence Perfume', 55.00, 'Perfumes and Fragrances', 'AVAILABLE'),
('Luxury Cologne Set', 130.00, 'Perfumes and Fragrances', 'AVAILABLE'),

-- Candles
('Scented Soy Candle (Lavender)', 25.00, 'Candles', 'AVAILABLE'),
('Aromatherapy Candle Set', 50.00, 'Candles', 'AVAILABLE'),
('Luxury Vanilla Candle', 30.00, 'Candles', 'AVAILABLE'),
('Personalized Candle with Name', 40.00, 'Candles', 'AVAILABLE'),
('Handmade Beeswax Candle', 20.00, 'Candles', 'AVAILABLE'),
('Woodwick Crackling Candle', 35.00, 'Candles', 'AVAILABLE'),
('Rose and Jasmine Scented Candle', 28.00, 'Candles', 'AVAILABLE'),
('Cinnamon and Apple Holiday Candle', 25.00, 'Candles', 'AVAILABLE'),
('Relaxing Spa Candle', 33.00, 'Candles', 'AVAILABLE'),
('Travel-Sized Candle Set', 23.00, 'Candles', 'AVAILABLE'),
('Ocean Breeze Candle', 27.00, 'Candles', 'AVAILABLE'),
('Coconut and Lime Scented Candle', 32.00, 'Candles', 'AVAILABLE'),
('Chocolate and Coffee Candle', 29.00, 'Candles', 'AVAILABLE'),
('Festive Christmas Candle', 30.00, 'Candles', 'AVAILABLE'),
('Meditation Scented Candle', 38.00, 'Candles', 'AVAILABLE');

COMMIT;
