CREATE USER gifty IDENTIFIED BY gifty;

GRANT CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE SESSION,
      CREATE SYNONYM,
      CREATE TABLE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE VIEW
  TO gifty;

ALTER USER gifty QUOTA UNLIMITED ON USERS;
